Handle tap disabled by timeout
Fixes crashes due to event timeout.

Connecting...
Connected.
2020-07-09 01:19:28.832 Python[17054:2096688] unrecognized type is 4294967294
2020-07-09 01:19:28.832 Python[17054:2096688] *** Assertion failure in -[NSEvent _initWithCGEvent:eventRef:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1671.60.109/AppKit.subproj/NSEvent.m:1977
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/shastry/.local/pipx/venvs/osxmpdkeys/lib/python3.8/site-packages/osxmmkeys/tap.py", line 51, in run
    Quartz.CFRunLoopRun()  # Only returns after stop() is called.
objc.error: NSInternalInconsistencyException - Invalid parameter not satisfying: _type > 0 && _type <= kCGSLastEventType